version: 1.0.0-beta.{build}

build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true

cache:
  - packages -> **\packages.config

install:
  - nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

skip_tags: true # Avoid building on Tags or Releases